### ISSUE TITLE
Usage with docker machine

### ISSUE THREAD

**Issue by lukasoppermann** [shipping-docker/php-app#10]
Hey,

so everything is working just fine using docker for mac. However, now I am trying the same with docker machine. I used a virtual box driver and get an ip "x.y.z"

When I go to "x.y.z" in the browser instead of the laravel app, I am getting a 404 error, what could I be doing wrong?

**Comment by fideloper** [comment]
File sharing is the likely culprit I'd think - Docker is presumably sharing a volume with the VirtualBox server which in turn is doing file sharing with your host computer (your Mac). Something could be going wrong in that setup.

When running Docker directly on linux, there is also an issue of file permissions that are "hidden" from us when we run Docker on Mac due to how file sharing works with the virtualization they use on Mac.

I'll try to make a video on that soon. Essentially you can see what user is running nginx/php-fpm (usually user `www-data`, with a user id of `33`), and try to match that user as the owner of the files on the linux server file system (your virtualbox vm). `chown -R 33 application/`

**Comment by lukasoppermann** [comment]
Okay, I figured it probably makes sense to deploy to digital ocean via docker machine and thus I would like to use first on a virtual box, to check if it is running there.
