### ISSUE TITLE
Deploy php app

### ISSUE THREAD

**Issue by lukasoppermann** [shipping-docker/php-app#7]
Hey,

I got another question: How do I deploy to something like digital ocean? I have my laravel app in a private github repo. 

I used to deploy via capistrano, can I continue doing this? This should update all files in the `./application` folder and it should be reflected on the server, correct?

**Comment by fideloper** [comment]
That's a big question I hope to answer in this video series (assuming you're using Docker in production). 

## Dev

In development you'd typically have code on your host machine (macintosh, or whatever you use as your development computer), so that you can edit it in an IDE and all that. This is our setup using `docker-compose.yml` here.

## Two general deployment approaches

In production, some people still share code via a volume (`-v` flag like we used with docker-compose).

* This means you do need to update your code on a server somewhere, and a capistrano-style update to replace files could likely work in that case
* This also means you can swap out your Docker instance separately from code

**However, more common is for people to build the code directly into their container.**

This means building a new image when you want to deploy code. Typically a Dockerfile is used to CP or MV the latest code (and any assets) directly into the container and pushing that container up to a registry ( like hub.docker.com, which you can use, or a private registry you host yourself). 

Pushing that newly built image (with your latest code) to production then becomes a matter of replacing containers (stopping old, starting new). This is often done using a load balancer to help with transitioning containers out/in without causing down time. However systems like Docker Swarm, Kubernetes, Mesos, Rancher (etc) usually do that for you. 

In the series I'll likely be covering Swarm with Rancher to accomplish all of this. Likely with the help of Jenkins to help automate testing and building docker images.

**Comment by lukasoppermann** [comment]
Hey, thanks. Will you also cover approaches that do not need payed services? Docker swarm is a service right? I am building rather small apps and will only update them a couple times a year, paying a monthly fee for a service just doesn't make sense for those projects. 😉

**Comment by fideloper** [comment]
Nope, Docker Swarm is part of Docker 1.12.

However, if you want a private repo for images from hub.docker.com, that costs money. BUT you can spin up your own private registry, which I will cover.

Either way, there will likely be some extra servers to pay for in a full setup for some automation (depending on if you want to automate it do it manually).

Fair warning: In a setup where you're only updating a few times a year, you might not see the benefits of Docker (although either way, it's worth learning at least for some local development / tricks).

**Comment by lukasoppermann** [comment]
Ahh, didn't know this, thanks. I think I actually can already see some benefits of using docker for my projects, so no worries.
