### ISSUE TITLE
Customizing php extensions

### ISSUE THREAD

**Issue by guiwoda** [shipping-docker/php-app#8]
Hey Chris!
I've been playing around with Docker for a couple of days, and I wanted to add php extensions to containers based on this image (particularily `php-curl`).

Would you recommend extending this image with my own `Dockerfile`? Or should I PR a change here to allow custom extensions with some sort of extension point (as MySQL does with env vars)?

Moreover, the [official php images](https://hub.docker.com/_/php/) provide some helper scripts to do this, but this image doesn't extend from them, so I couldn't use those. Why did you choose to install php instead of extending the official images?

Thanks a lot for this video series!
Cheers

**Comment by guiwoda** [comment]
_By the way, this is in no way an issue, I just figured I could use this as a conversation point. I know I can point directly to the `php:7.0` image on my docker-compose file. It's more about learning what's best!_

**Comment by fideloper** [comment]
Hi!

## PHP-Curl

For specifically `shippingdocker/php`, a PR sounds great for `php-curl`, as that's definitely a common one that I should have added in (I assumed it was there by default).

If you wanted to extend your own with a new `Dockerfile`, you definitely can - that's one of Docker's intended uses.

## Official PHP Image vs My Own

I didn't do the official image purely because using the Ubuntu base image and installing from `apt-get` is (probably) more familiar and easier to grok to new-comers.

The official repository is definitely one I've used, but I've found the process of adding on additional modules to be a bit wonky - you use their own command that's specific to the PHP setup in that repository, which gets into talking about methods of building a container that was more advanced than I wanted for this mini-course.

Each additional module you want to install for PHP typically also comes with some base libraries to install as well, but it's hard to find information on which, so I'd get a lot of support asking questions about installing modules which would just lead to everyone googling around and experimenting until it worked.

I didn't want that to be anyone's first experience with Docker, that process sucks!

If you're comfortable with that process tho, give the official PHP images a try as well - They've worked pretty well for me so far, but takes a bit of googling to add custom modules.

**Comment by guiwoda** [comment]
That's great info!
I think I'll extend with a `Dockerfile` that also installs extra extensions through `apt`. Maybe try out the official ones when I'm more comfortable with the whole thing.

Thanks again!

**Comment by fideloper** [comment]
Cool -
If/when you do, here's what it looks like to extend their `Dockerfile` and add a module. In this case, I added the `php-imap` module:

```
FROM php:7.0-cli

MAINTAINER Chris Fidao

RUN apt-get update \
    && apt-get -y install libssl-dev libc-client2007e-dev libkrb5-dev \
    && docker-php-ext-configure imap --with-imap-ssl --with-kerberos \
    && docker-php-ext-install imap
```

It's a minimal Debian box under the hood (not Ubuntu, but close enough - we still get the `apt-get` command), and has two commands specific to the container:

* `docker-php-ext-configure`
* `docker-php-ext-install`

However there isn't really documentation for the libraries needed under the hood for all the other extensions/modules you may want to install. In general, it takes some googling around.
